### ISSUE TITLE
Model importation

### ISSUE THREAD

**Issue by danielscos** [GeorgesCoding/Chess#5]
If I wanted to import a .h5 how would I import it?

**Comment by georgescoding** [comment]
I'm not sure as I haven't worked with HDF5. What are you trying to use it for?

**Comment by danielscos** [comment]
Well, instead of using your ai I want to import a trained model.
I want to train a chess neural network myself and then import it

**Comment by georgescoding** [comment]
I'm quite busy with school right now so I won't be able to help too much. But to edit the AI, remove the part in Main.py that receives the returned value from the minimax function. Then, replace the variables that were supposed to be the returned values from the minimax function with the returned values of your own AI. You would have to convert your AI's decision into the various components of moving the piece: the old position of the piece being moved, the new position and the piece type. The positions should be in terms of the y,x coordinates of the board (from 0 to 7) and the piece type should follow the convention I used to represent pieces. Good luck!
